version: '3.1'
services:
    mongo_db:
        image: mongo
        ports:
            - 27017:27017
        environment: 
            MONGO_INITDB_ROOT_USERNAME : admin
            MONGO_INITDB_ROOT_PASSWORD : password
    mongo_express:
        image: mongo-express
        ports:
            - 8081:8081
        environment:
            ME_CONFIG_MONGODB_ADMINUSERNAME : admin
            ME_CONFIG_MONGODB_ADMINPASSWORD : password
            ME_CONFIG_MONGODB_SERVER : mongo_db
            ME_CONFIG_BASICAUTH_USERNAME : veera
            ME_CONFIG_BASICAUTH_PASSWORD : password

